// Mocks generated by Mockito 5.4.5 from annotations
// in isolate_channel/test/common.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:isolate' as _i5;

import 'package:isolate_channel/src/model/internal/method_invocation.dart'
    as _i3;
import 'package:isolate_channel/src/model/isolate_connection.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IsolateConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsolateConnection extends _i1.Mock implements _i2.IsolateConnection {
  @override
  int get connections =>
      (super.noSuchMethod(
            Invocation.getter(#connections),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void send(_i3.MethodInvocation? invocation) => super.noSuchMethod(
    Invocation.method(#send, [invocation]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Stream<_i3.MethodInvocation> methodInvocations(String? channel) =>
      (super.noSuchMethod(
            Invocation.method(#methodInvocations, [channel]),
            returnValue: _i4.Stream<_i3.MethodInvocation>.empty(),
            returnValueForMissingStub: _i4.Stream<_i3.MethodInvocation>.empty(),
          )
          as _i4.Stream<_i3.MethodInvocation>);

  @override
  void isolateConnected(_i5.SendPort? sendPort) => super.noSuchMethod(
    Invocation.method(#isolateConnected, [sendPort]),
    returnValueForMissingStub: null,
  );

  @override
  void isolateDisconnected(_i5.SendPort? sendPort) => super.noSuchMethod(
    Invocation.method(#isolateDisconnected, [sendPort]),
    returnValueForMissingStub: null,
  );

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
